name: go-prompt
lang: go
git:
  enable: true
  hook:
    enable: true
github:
  enable: true
gitignore:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
make:
  enable: true
  enable_updates: true
  update_makefile: false